# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

APP_BUILD_NUMBER = ENV["APP_BUILD_NUMBER"]
APP_CHANGELOG = ENV["APP_CHANGELOG"]
MATCH_PASSWORD = ENV["MATCH_PASSWORD"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

platform :ios do
  desc "Push a new internal beta build to TestFlight"
  lane :internal_beta do

    setup_ci()

    app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT
    )

    match(
      type: 'appstore',
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      verbose: true,
      generate_apple_certs: true,
      app_identifier: ["com.octopuscommunity.sdk.sample"]
    )
    
    build_app(
      workspace: "OctopusSample.xcworkspace", 
      scheme: "OctopusSample",
      xcargs: "BUILD_NUMBER='#{APP_BUILD_NUMBER}'",
      export_method: "app-store",
      skip_profile_detection: true,
      export_options: {
        testFlightInternalTestingOnly: true
      }
    )

    upload_to_testflight(
      changelog: APP_CHANGELOG,
      distribute_external: false,
      notify_external_testers: false
    )
  end
end
