//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: com/octopuscommunity/ContentReviewServiceProto.proto
//
#if canImport(GRPC)
import GRPC
#else
import GRPCSwift
#endif
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Com_Octopuscommunity_ContentReviewServiceClient`, then call methods of this protocol to make API calls.
public protocol Com_Octopuscommunity_ContentReviewServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? { get }

  func listContentReview(
    _ request: Com_Octopuscommunity_ListContentReviewRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse>

  func validateContentReview(
    _ request: Com_Octopuscommunity_ValidateContentReviewRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse>

  func bulkValidateContentReview(
    _ request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse>

  func sendToSupport(
    _ request: Com_Octopuscommunity_SendToSupportRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse>
}

extension Com_Octopuscommunity_ContentReviewServiceClientProtocol {
  public var serviceName: String {
    return "com.octopuscommunity.ContentReviewService"
  }

  /// Unary call to ListContentReview
  ///
  /// - Parameters:
  ///   - request: Request to send to ListContentReview.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listContentReview(
    _ request: Com_Octopuscommunity_ListContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.listContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListContentReviewInterceptors() ?? []
    )
  }

  /// Unary call to ValidateContentReview
  ///
  /// - Parameters:
  ///   - request: Request to send to ValidateContentReview.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func validateContentReview(
    _ request: Com_Octopuscommunity_ValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.validateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateContentReviewInterceptors() ?? []
    )
  }

  /// Unary call to BulkValidateContentReview
  ///
  /// - Parameters:
  ///   - request: Request to send to BulkValidateContentReview.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func bulkValidateContentReview(
    _ request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.bulkValidateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBulkValidateContentReviewInterceptors() ?? []
    )
  }

  /// Unary call to SendToSupport
  ///
  /// - Parameters:
  ///   - request: Request to send to SendToSupport.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func sendToSupport(
    _ request: Com_Octopuscommunity_SendToSupportRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.sendToSupport.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendToSupportInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Com_Octopuscommunity_ContentReviewServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Com_Octopuscommunity_ContentReviewServiceNIOClient")
public final class Com_Octopuscommunity_ContentReviewServiceClient: Com_Octopuscommunity_ContentReviewServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the com.octopuscommunity.ContentReviewService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Com_Octopuscommunity_ContentReviewServiceNIOClient: Com_Octopuscommunity_ContentReviewServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the com.octopuscommunity.ContentReviewService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_ContentReviewServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? { get }

  func makeListContentReviewCall(
    _ request: Com_Octopuscommunity_ListContentReviewRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse>

  func makeValidateContentReviewCall(
    _ request: Com_Octopuscommunity_ValidateContentReviewRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse>

  func makeBulkValidateContentReviewCall(
    _ request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse>

  func makeSendToSupportCall(
    _ request: Com_Octopuscommunity_SendToSupportRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ContentReviewServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_ContentReviewServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeListContentReviewCall(
    _ request: Com_Octopuscommunity_ListContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.listContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListContentReviewInterceptors() ?? []
    )
  }

  public func makeValidateContentReviewCall(
    _ request: Com_Octopuscommunity_ValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.validateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateContentReviewInterceptors() ?? []
    )
  }

  public func makeBulkValidateContentReviewCall(
    _ request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.bulkValidateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBulkValidateContentReviewInterceptors() ?? []
    )
  }

  public func makeSendToSupportCall(
    _ request: Com_Octopuscommunity_SendToSupportRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.sendToSupport.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendToSupportInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ContentReviewServiceAsyncClientProtocol {
  public func listContentReview(
    _ request: Com_Octopuscommunity_ListContentReviewRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_ListContentReviewResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.listContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListContentReviewInterceptors() ?? []
    )
  }

  public func validateContentReview(
    _ request: Com_Octopuscommunity_ValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_ValidateContentReviewResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.validateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeValidateContentReviewInterceptors() ?? []
    )
  }

  public func bulkValidateContentReview(
    _ request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_BulkValidateContentReviewResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.bulkValidateContentReview.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBulkValidateContentReviewInterceptors() ?? []
    )
  }

  public func sendToSupport(
    _ request: Com_Octopuscommunity_SendToSupportRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_SendToSupportResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.sendToSupport.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendToSupportInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Com_Octopuscommunity_ContentReviewServiceAsyncClient: Com_Octopuscommunity_ContentReviewServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Com_Octopuscommunity_ContentReviewServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'listContentReview'.
  func makeListContentReviewInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse>]

  /// - Returns: Interceptors to use when invoking 'validateContentReview'.
  func makeValidateContentReviewInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse>]

  /// - Returns: Interceptors to use when invoking 'bulkValidateContentReview'.
  func makeBulkValidateContentReviewInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse>]

  /// - Returns: Interceptors to use when invoking 'sendToSupport'.
  func makeSendToSupportInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse>]
}

public enum Com_Octopuscommunity_ContentReviewServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ContentReviewService",
    fullName: "com.octopuscommunity.ContentReviewService",
    methods: [
      Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.listContentReview,
      Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.validateContentReview,
      Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.bulkValidateContentReview,
      Com_Octopuscommunity_ContentReviewServiceClientMetadata.Methods.sendToSupport,
    ]
  )

  public enum Methods {
    public static let listContentReview = GRPCMethodDescriptor(
      name: "ListContentReview",
      path: "/com.octopuscommunity.ContentReviewService/ListContentReview",
      type: GRPCCallType.unary
    )

    public static let validateContentReview = GRPCMethodDescriptor(
      name: "ValidateContentReview",
      path: "/com.octopuscommunity.ContentReviewService/ValidateContentReview",
      type: GRPCCallType.unary
    )

    public static let bulkValidateContentReview = GRPCMethodDescriptor(
      name: "BulkValidateContentReview",
      path: "/com.octopuscommunity.ContentReviewService/BulkValidateContentReview",
      type: GRPCCallType.unary
    )

    public static let sendToSupport = GRPCMethodDescriptor(
      name: "SendToSupport",
      path: "/com.octopuscommunity.ContentReviewService/SendToSupport",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Com_Octopuscommunity_ContentReviewServiceProvider: CallHandlerProvider {
  var interceptors: Com_Octopuscommunity_ContentReviewServiceServerInterceptorFactoryProtocol? { get }

  func listContentReview(request: Com_Octopuscommunity_ListContentReviewRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_ListContentReviewResponse>

  func validateContentReview(request: Com_Octopuscommunity_ValidateContentReviewRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_ValidateContentReviewResponse>

  func bulkValidateContentReview(request: Com_Octopuscommunity_BulkValidateContentReviewRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_BulkValidateContentReviewResponse>

  func sendToSupport(request: Com_Octopuscommunity_SendToSupportRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_SendToSupportResponse>
}

extension Com_Octopuscommunity_ContentReviewServiceProvider {
  public var serviceName: Substring {
    return Com_Octopuscommunity_ContentReviewServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ListContentReview":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListContentReviewResponse>(),
        interceptors: self.interceptors?.makeListContentReviewInterceptors() ?? [],
        userFunction: self.listContentReview(request:context:)
      )

    case "ValidateContentReview":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ValidateContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ValidateContentReviewResponse>(),
        interceptors: self.interceptors?.makeValidateContentReviewInterceptors() ?? [],
        userFunction: self.validateContentReview(request:context:)
      )

    case "BulkValidateContentReview":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_BulkValidateContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_BulkValidateContentReviewResponse>(),
        interceptors: self.interceptors?.makeBulkValidateContentReviewInterceptors() ?? [],
        userFunction: self.bulkValidateContentReview(request:context:)
      )

    case "SendToSupport":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_SendToSupportRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_SendToSupportResponse>(),
        interceptors: self.interceptors?.makeSendToSupportInterceptors() ?? [],
        userFunction: self.sendToSupport(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_ContentReviewServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_ContentReviewServiceServerInterceptorFactoryProtocol? { get }

  func listContentReview(
    request: Com_Octopuscommunity_ListContentReviewRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_ListContentReviewResponse

  func validateContentReview(
    request: Com_Octopuscommunity_ValidateContentReviewRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_ValidateContentReviewResponse

  func bulkValidateContentReview(
    request: Com_Octopuscommunity_BulkValidateContentReviewRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_BulkValidateContentReviewResponse

  func sendToSupport(
    request: Com_Octopuscommunity_SendToSupportRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_SendToSupportResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ContentReviewServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_ContentReviewServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Com_Octopuscommunity_ContentReviewServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Com_Octopuscommunity_ContentReviewServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ListContentReview":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListContentReviewResponse>(),
        interceptors: self.interceptors?.makeListContentReviewInterceptors() ?? [],
        wrapping: { try await self.listContentReview(request: $0, context: $1) }
      )

    case "ValidateContentReview":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ValidateContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ValidateContentReviewResponse>(),
        interceptors: self.interceptors?.makeValidateContentReviewInterceptors() ?? [],
        wrapping: { try await self.validateContentReview(request: $0, context: $1) }
      )

    case "BulkValidateContentReview":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_BulkValidateContentReviewRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_BulkValidateContentReviewResponse>(),
        interceptors: self.interceptors?.makeBulkValidateContentReviewInterceptors() ?? [],
        wrapping: { try await self.bulkValidateContentReview(request: $0, context: $1) }
      )

    case "SendToSupport":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_SendToSupportRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_SendToSupportResponse>(),
        interceptors: self.interceptors?.makeSendToSupportInterceptors() ?? [],
        wrapping: { try await self.sendToSupport(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Com_Octopuscommunity_ContentReviewServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'listContentReview'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListContentReviewInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_ListContentReviewRequest, Com_Octopuscommunity_ListContentReviewResponse>]

  /// - Returns: Interceptors to use when handling 'validateContentReview'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeValidateContentReviewInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_ValidateContentReviewRequest, Com_Octopuscommunity_ValidateContentReviewResponse>]

  /// - Returns: Interceptors to use when handling 'bulkValidateContentReview'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeBulkValidateContentReviewInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_BulkValidateContentReviewRequest, Com_Octopuscommunity_BulkValidateContentReviewResponse>]

  /// - Returns: Interceptors to use when handling 'sendToSupport'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSendToSupportInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_SendToSupportRequest, Com_Octopuscommunity_SendToSupportResponse>]
}

public enum Com_Octopuscommunity_ContentReviewServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ContentReviewService",
    fullName: "com.octopuscommunity.ContentReviewService",
    methods: [
      Com_Octopuscommunity_ContentReviewServiceServerMetadata.Methods.listContentReview,
      Com_Octopuscommunity_ContentReviewServiceServerMetadata.Methods.validateContentReview,
      Com_Octopuscommunity_ContentReviewServiceServerMetadata.Methods.bulkValidateContentReview,
      Com_Octopuscommunity_ContentReviewServiceServerMetadata.Methods.sendToSupport,
    ]
  )

  public enum Methods {
    public static let listContentReview = GRPCMethodDescriptor(
      name: "ListContentReview",
      path: "/com.octopuscommunity.ContentReviewService/ListContentReview",
      type: GRPCCallType.unary
    )

    public static let validateContentReview = GRPCMethodDescriptor(
      name: "ValidateContentReview",
      path: "/com.octopuscommunity.ContentReviewService/ValidateContentReview",
      type: GRPCCallType.unary
    )

    public static let bulkValidateContentReview = GRPCMethodDescriptor(
      name: "BulkValidateContentReview",
      path: "/com.octopuscommunity.ContentReviewService/BulkValidateContentReview",
      type: GRPCCallType.unary
    )

    public static let sendToSupport = GRPCMethodDescriptor(
      name: "SendToSupport",
      path: "/com.octopuscommunity.ContentReviewService/SendToSupport",
      type: GRPCCallType.unary
    )
  }
}
