//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: com/octopuscommunity/MediaServiceProto.proto
//
#if canImport(GRPC)
import GRPC
#else
import GRPCSwift
#endif
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Com_Octopuscommunity_MediaServiceClient`, then call methods of this protocol to make API calls.
public protocol Com_Octopuscommunity_MediaServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? { get }

  func getMedia(
    _ request: Com_Octopuscommunity_GetMediaRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse>
}

extension Com_Octopuscommunity_MediaServiceClientProtocol {
  public var serviceName: String {
    return "com.octopuscommunity.MediaService"
  }

  /// For Back-Office
  ///
  /// - Parameters:
  ///   - request: Request to send to GetMedia.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getMedia(
    _ request: Com_Octopuscommunity_GetMediaRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_MediaServiceClientMetadata.Methods.getMedia.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMediaInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Com_Octopuscommunity_MediaServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Com_Octopuscommunity_MediaServiceNIOClient")
public final class Com_Octopuscommunity_MediaServiceClient: Com_Octopuscommunity_MediaServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the com.octopuscommunity.MediaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Com_Octopuscommunity_MediaServiceNIOClient: Com_Octopuscommunity_MediaServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the com.octopuscommunity.MediaService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_MediaServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? { get }

  func makeGetMediaCall(
    _ request: Com_Octopuscommunity_GetMediaRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_MediaServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_MediaServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeGetMediaCall(
    _ request: Com_Octopuscommunity_GetMediaRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_MediaServiceClientMetadata.Methods.getMedia.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMediaInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_MediaServiceAsyncClientProtocol {
  public func getMedia(
    _ request: Com_Octopuscommunity_GetMediaRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_GetMediaResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_MediaServiceClientMetadata.Methods.getMedia.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetMediaInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Com_Octopuscommunity_MediaServiceAsyncClient: Com_Octopuscommunity_MediaServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Com_Octopuscommunity_MediaServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getMedia'.
  func makeGetMediaInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse>]
}

public enum Com_Octopuscommunity_MediaServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MediaService",
    fullName: "com.octopuscommunity.MediaService",
    methods: [
      Com_Octopuscommunity_MediaServiceClientMetadata.Methods.getMedia,
    ]
  )

  public enum Methods {
    public static let getMedia = GRPCMethodDescriptor(
      name: "GetMedia",
      path: "/com.octopuscommunity.MediaService/GetMedia",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Com_Octopuscommunity_MediaServiceProvider: CallHandlerProvider {
  var interceptors: Com_Octopuscommunity_MediaServiceServerInterceptorFactoryProtocol? { get }

  /// For Back-Office
  func getMedia(request: Com_Octopuscommunity_GetMediaRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_GetMediaResponse>
}

extension Com_Octopuscommunity_MediaServiceProvider {
  public var serviceName: Substring {
    return Com_Octopuscommunity_MediaServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetMedia":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_GetMediaRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_GetMediaResponse>(),
        interceptors: self.interceptors?.makeGetMediaInterceptors() ?? [],
        userFunction: self.getMedia(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_MediaServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_MediaServiceServerInterceptorFactoryProtocol? { get }

  /// For Back-Office
  func getMedia(
    request: Com_Octopuscommunity_GetMediaRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_GetMediaResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_MediaServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_MediaServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Com_Octopuscommunity_MediaServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Com_Octopuscommunity_MediaServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetMedia":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_GetMediaRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_GetMediaResponse>(),
        interceptors: self.interceptors?.makeGetMediaInterceptors() ?? [],
        wrapping: { try await self.getMedia(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Com_Octopuscommunity_MediaServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getMedia'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetMediaInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_GetMediaRequest, Com_Octopuscommunity_GetMediaResponse>]
}

public enum Com_Octopuscommunity_MediaServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MediaService",
    fullName: "com.octopuscommunity.MediaService",
    methods: [
      Com_Octopuscommunity_MediaServiceServerMetadata.Methods.getMedia,
    ]
  )

  public enum Methods {
    public static let getMedia = GRPCMethodDescriptor(
      name: "GetMedia",
      path: "/com.octopuscommunity.MediaService/GetMedia",
      type: GRPCCallType.unary
    )
  }
}
