//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: com/octopuscommunity/ModerationPolicyServiceProto.proto
//
#if canImport(GRPC)
import GRPC
#else
import GRPCSwift
#endif
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Com_Octopuscommunity_ModerationPolicyServiceClient`, then call methods of this protocol to make API calls.
public protocol Com_Octopuscommunity_ModerationPolicyServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? { get }

  func createPolicy(
    _ request: Com_Octopuscommunity_CreatePolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse>

  func listPolicies(
    _ request: Com_Octopuscommunity_ListPoliciesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse>

  func updatePolicy(
    _ request: Com_Octopuscommunity_UpdatePolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse>

  func deletePolicy(
    _ request: Com_Octopuscommunity_DeletePolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse>

  func createDefaultAttachment(
    _ request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse>

  func listCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>

  func deleteCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>

  func updateCommunityPolicyAttachment(
    _ request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>

  func listAttachedPolicies(
    _ request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse>
}

extension Com_Octopuscommunity_ModerationPolicyServiceClientProtocol {
  public var serviceName: String {
    return "com.octopuscommunity.ModerationPolicyService"
  }

  /// Octopus-admin calls
  ///
  /// - Parameters:
  ///   - request: Request to send to CreatePolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createPolicy(
    _ request: Com_Octopuscommunity_CreatePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreatePolicyInterceptors() ?? []
    )
  }

  /// Unary call to ListPolicies
  ///
  /// - Parameters:
  ///   - request: Request to send to ListPolicies.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listPolicies(
    _ request: Com_Octopuscommunity_ListPoliciesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPoliciesInterceptors() ?? []
    )
  }

  /// Unary call to UpdatePolicy
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdatePolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updatePolicy(
    _ request: Com_Octopuscommunity_UpdatePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updatePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePolicyInterceptors() ?? []
    )
  }

  /// Unary call to DeletePolicy
  ///
  /// - Parameters:
  ///   - request: Request to send to DeletePolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deletePolicy(
    _ request: Com_Octopuscommunity_DeletePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deletePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePolicyInterceptors() ?? []
    )
  }

  /// Unary call to CreateDefaultAttachment
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateDefaultAttachment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createDefaultAttachment(
    _ request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createDefaultAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateDefaultAttachmentInterceptors() ?? []
    )
  }

  /// Unary call to ListCommunityPolicyAttachments
  ///
  /// - Parameters:
  ///   - request: Request to send to ListCommunityPolicyAttachments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  /// Unary call to DeleteCommunityPolicyAttachments
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteCommunityPolicyAttachments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deleteCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  /// Client BO calls
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateCommunityPolicyAttachment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateCommunityPolicyAttachment(
    _ request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updateCommunityPolicyAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateCommunityPolicyAttachmentInterceptors() ?? []
    )
  }

  /// Unary call to ListAttachedPolicies
  ///
  /// - Parameters:
  ///   - request: Request to send to ListAttachedPolicies.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listAttachedPolicies(
    _ request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse> {
    return self.makeUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listAttachedPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListAttachedPoliciesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Com_Octopuscommunity_ModerationPolicyServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Com_Octopuscommunity_ModerationPolicyServiceNIOClient")
public final class Com_Octopuscommunity_ModerationPolicyServiceClient: Com_Octopuscommunity_ModerationPolicyServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the com.octopuscommunity.ModerationPolicyService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Com_Octopuscommunity_ModerationPolicyServiceNIOClient: Com_Octopuscommunity_ModerationPolicyServiceClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the com.octopuscommunity.ModerationPolicyService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_ModerationPolicyServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? { get }

  func makeCreatePolicyCall(
    _ request: Com_Octopuscommunity_CreatePolicyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse>

  func makeListPoliciesCall(
    _ request: Com_Octopuscommunity_ListPoliciesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse>

  func makeUpdatePolicyCall(
    _ request: Com_Octopuscommunity_UpdatePolicyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse>

  func makeDeletePolicyCall(
    _ request: Com_Octopuscommunity_DeletePolicyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse>

  func makeCreateDefaultAttachmentCall(
    _ request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse>

  func makeListCommunityPolicyAttachmentsCall(
    _ request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>

  func makeDeleteCommunityPolicyAttachmentsCall(
    _ request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>

  func makeUpdateCommunityPolicyAttachmentCall(
    _ request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>

  func makeListAttachedPoliciesCall(
    _ request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ModerationPolicyServiceAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.serviceDescriptor
  }

  public var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeCreatePolicyCall(
    _ request: Com_Octopuscommunity_CreatePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreatePolicyInterceptors() ?? []
    )
  }

  public func makeListPoliciesCall(
    _ request: Com_Octopuscommunity_ListPoliciesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPoliciesInterceptors() ?? []
    )
  }

  public func makeUpdatePolicyCall(
    _ request: Com_Octopuscommunity_UpdatePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updatePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePolicyInterceptors() ?? []
    )
  }

  public func makeDeletePolicyCall(
    _ request: Com_Octopuscommunity_DeletePolicyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deletePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePolicyInterceptors() ?? []
    )
  }

  public func makeCreateDefaultAttachmentCall(
    _ request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createDefaultAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateDefaultAttachmentInterceptors() ?? []
    )
  }

  public func makeListCommunityPolicyAttachmentsCall(
    _ request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  public func makeDeleteCommunityPolicyAttachmentsCall(
    _ request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deleteCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  public func makeUpdateCommunityPolicyAttachmentCall(
    _ request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updateCommunityPolicyAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateCommunityPolicyAttachmentInterceptors() ?? []
    )
  }

  public func makeListAttachedPoliciesCall(
    _ request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse> {
    return self.makeAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listAttachedPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListAttachedPoliciesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ModerationPolicyServiceAsyncClientProtocol {
  public func createPolicy(
    _ request: Com_Octopuscommunity_CreatePolicyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_CreatePolicyResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createPolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreatePolicyInterceptors() ?? []
    )
  }

  public func listPolicies(
    _ request: Com_Octopuscommunity_ListPoliciesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_ListPoliciesResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPoliciesInterceptors() ?? []
    )
  }

  public func updatePolicy(
    _ request: Com_Octopuscommunity_UpdatePolicyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_UpdatePolicyResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updatePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePolicyInterceptors() ?? []
    )
  }

  public func deletePolicy(
    _ request: Com_Octopuscommunity_DeletePolicyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_DeletePolicyResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deletePolicy.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePolicyInterceptors() ?? []
    )
  }

  public func createDefaultAttachment(
    _ request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_CreateDefaultAttachmentResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createDefaultAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateDefaultAttachmentInterceptors() ?? []
    )
  }

  public func listCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  public func deleteCommunityPolicyAttachments(
    _ request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deleteCommunityPolicyAttachments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteCommunityPolicyAttachmentsInterceptors() ?? []
    )
  }

  public func updateCommunityPolicyAttachment(
    _ request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updateCommunityPolicyAttachment.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateCommunityPolicyAttachmentInterceptors() ?? []
    )
  }

  public func listAttachedPolicies(
    _ request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Com_Octopuscommunity_ListAttachedPoliciesResponse {
    return try await self.performAsyncUnaryCall(
      path: Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listAttachedPolicies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListAttachedPoliciesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Com_Octopuscommunity_ModerationPolicyServiceAsyncClient: Com_Octopuscommunity_ModerationPolicyServiceAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Com_Octopuscommunity_ModerationPolicyServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'createPolicy'.
  func makeCreatePolicyInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse>]

  /// - Returns: Interceptors to use when invoking 'listPolicies'.
  func makeListPoliciesInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse>]

  /// - Returns: Interceptors to use when invoking 'updatePolicy'.
  func makeUpdatePolicyInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse>]

  /// - Returns: Interceptors to use when invoking 'deletePolicy'.
  func makeDeletePolicyInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse>]

  /// - Returns: Interceptors to use when invoking 'createDefaultAttachment'.
  func makeCreateDefaultAttachmentInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse>]

  /// - Returns: Interceptors to use when invoking 'listCommunityPolicyAttachments'.
  func makeListCommunityPolicyAttachmentsInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteCommunityPolicyAttachments'.
  func makeDeleteCommunityPolicyAttachmentsInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>]

  /// - Returns: Interceptors to use when invoking 'updateCommunityPolicyAttachment'.
  func makeUpdateCommunityPolicyAttachmentInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>]

  /// - Returns: Interceptors to use when invoking 'listAttachedPolicies'.
  func makeListAttachedPoliciesInterceptors() -> [ClientInterceptor<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse>]
}

public enum Com_Octopuscommunity_ModerationPolicyServiceClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ModerationPolicyService",
    fullName: "com.octopuscommunity.ModerationPolicyService",
    methods: [
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createPolicy,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listPolicies,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updatePolicy,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deletePolicy,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.createDefaultAttachment,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listCommunityPolicyAttachments,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.deleteCommunityPolicyAttachments,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.updateCommunityPolicyAttachment,
      Com_Octopuscommunity_ModerationPolicyServiceClientMetadata.Methods.listAttachedPolicies,
    ]
  )

  public enum Methods {
    public static let createPolicy = GRPCMethodDescriptor(
      name: "CreatePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/CreatePolicy",
      type: GRPCCallType.unary
    )

    public static let listPolicies = GRPCMethodDescriptor(
      name: "ListPolicies",
      path: "/com.octopuscommunity.ModerationPolicyService/ListPolicies",
      type: GRPCCallType.unary
    )

    public static let updatePolicy = GRPCMethodDescriptor(
      name: "UpdatePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/UpdatePolicy",
      type: GRPCCallType.unary
    )

    public static let deletePolicy = GRPCMethodDescriptor(
      name: "DeletePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/DeletePolicy",
      type: GRPCCallType.unary
    )

    public static let createDefaultAttachment = GRPCMethodDescriptor(
      name: "CreateDefaultAttachment",
      path: "/com.octopuscommunity.ModerationPolicyService/CreateDefaultAttachment",
      type: GRPCCallType.unary
    )

    public static let listCommunityPolicyAttachments = GRPCMethodDescriptor(
      name: "ListCommunityPolicyAttachments",
      path: "/com.octopuscommunity.ModerationPolicyService/ListCommunityPolicyAttachments",
      type: GRPCCallType.unary
    )

    public static let deleteCommunityPolicyAttachments = GRPCMethodDescriptor(
      name: "DeleteCommunityPolicyAttachments",
      path: "/com.octopuscommunity.ModerationPolicyService/DeleteCommunityPolicyAttachments",
      type: GRPCCallType.unary
    )

    public static let updateCommunityPolicyAttachment = GRPCMethodDescriptor(
      name: "UpdateCommunityPolicyAttachment",
      path: "/com.octopuscommunity.ModerationPolicyService/UpdateCommunityPolicyAttachment",
      type: GRPCCallType.unary
    )

    public static let listAttachedPolicies = GRPCMethodDescriptor(
      name: "ListAttachedPolicies",
      path: "/com.octopuscommunity.ModerationPolicyService/ListAttachedPolicies",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol Com_Octopuscommunity_ModerationPolicyServiceProvider: CallHandlerProvider {
  var interceptors: Com_Octopuscommunity_ModerationPolicyServiceServerInterceptorFactoryProtocol? { get }

  /// Octopus-admin calls
  func createPolicy(request: Com_Octopuscommunity_CreatePolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_CreatePolicyResponse>

  func listPolicies(request: Com_Octopuscommunity_ListPoliciesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_ListPoliciesResponse>

  func updatePolicy(request: Com_Octopuscommunity_UpdatePolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_UpdatePolicyResponse>

  func deletePolicy(request: Com_Octopuscommunity_DeletePolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_DeletePolicyResponse>

  func createDefaultAttachment(request: Com_Octopuscommunity_CreateDefaultAttachmentRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_CreateDefaultAttachmentResponse>

  func listCommunityPolicyAttachments(request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>

  func deleteCommunityPolicyAttachments(request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>

  /// Client BO calls
  func updateCommunityPolicyAttachment(request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>

  func listAttachedPolicies(request: Com_Octopuscommunity_ListAttachedPoliciesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Com_Octopuscommunity_ListAttachedPoliciesResponse>
}

extension Com_Octopuscommunity_ModerationPolicyServiceProvider {
  public var serviceName: Substring {
    return Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreatePolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_CreatePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_CreatePolicyResponse>(),
        interceptors: self.interceptors?.makeCreatePolicyInterceptors() ?? [],
        userFunction: self.createPolicy(request:context:)
      )

    case "ListPolicies":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListPoliciesRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListPoliciesResponse>(),
        interceptors: self.interceptors?.makeListPoliciesInterceptors() ?? [],
        userFunction: self.listPolicies(request:context:)
      )

    case "UpdatePolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_UpdatePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_UpdatePolicyResponse>(),
        interceptors: self.interceptors?.makeUpdatePolicyInterceptors() ?? [],
        userFunction: self.updatePolicy(request:context:)
      )

    case "DeletePolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_DeletePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_DeletePolicyResponse>(),
        interceptors: self.interceptors?.makeDeletePolicyInterceptors() ?? [],
        userFunction: self.deletePolicy(request:context:)
      )

    case "CreateDefaultAttachment":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_CreateDefaultAttachmentRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_CreateDefaultAttachmentResponse>(),
        interceptors: self.interceptors?.makeCreateDefaultAttachmentInterceptors() ?? [],
        userFunction: self.createDefaultAttachment(request:context:)
      )

    case "ListCommunityPolicyAttachments":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>(),
        interceptors: self.interceptors?.makeListCommunityPolicyAttachmentsInterceptors() ?? [],
        userFunction: self.listCommunityPolicyAttachments(request:context:)
      )

    case "DeleteCommunityPolicyAttachments":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>(),
        interceptors: self.interceptors?.makeDeleteCommunityPolicyAttachmentsInterceptors() ?? [],
        userFunction: self.deleteCommunityPolicyAttachments(request:context:)
      )

    case "UpdateCommunityPolicyAttachment":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>(),
        interceptors: self.interceptors?.makeUpdateCommunityPolicyAttachmentInterceptors() ?? [],
        userFunction: self.updateCommunityPolicyAttachment(request:context:)
      )

    case "ListAttachedPolicies":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListAttachedPoliciesRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListAttachedPoliciesResponse>(),
        interceptors: self.interceptors?.makeListAttachedPoliciesInterceptors() ?? [],
        userFunction: self.listAttachedPolicies(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Com_Octopuscommunity_ModerationPolicyServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Com_Octopuscommunity_ModerationPolicyServiceServerInterceptorFactoryProtocol? { get }

  /// Octopus-admin calls
  func createPolicy(
    request: Com_Octopuscommunity_CreatePolicyRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_CreatePolicyResponse

  func listPolicies(
    request: Com_Octopuscommunity_ListPoliciesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_ListPoliciesResponse

  func updatePolicy(
    request: Com_Octopuscommunity_UpdatePolicyRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_UpdatePolicyResponse

  func deletePolicy(
    request: Com_Octopuscommunity_DeletePolicyRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_DeletePolicyResponse

  func createDefaultAttachment(
    request: Com_Octopuscommunity_CreateDefaultAttachmentRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_CreateDefaultAttachmentResponse

  func listCommunityPolicyAttachments(
    request: Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse

  func deleteCommunityPolicyAttachments(
    request: Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse

  /// Client BO calls
  func updateCommunityPolicyAttachment(
    request: Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse

  func listAttachedPolicies(
    request: Com_Octopuscommunity_ListAttachedPoliciesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Com_Octopuscommunity_ListAttachedPoliciesResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Com_Octopuscommunity_ModerationPolicyServiceAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Com_Octopuscommunity_ModerationPolicyServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreatePolicy":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_CreatePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_CreatePolicyResponse>(),
        interceptors: self.interceptors?.makeCreatePolicyInterceptors() ?? [],
        wrapping: { try await self.createPolicy(request: $0, context: $1) }
      )

    case "ListPolicies":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListPoliciesRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListPoliciesResponse>(),
        interceptors: self.interceptors?.makeListPoliciesInterceptors() ?? [],
        wrapping: { try await self.listPolicies(request: $0, context: $1) }
      )

    case "UpdatePolicy":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_UpdatePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_UpdatePolicyResponse>(),
        interceptors: self.interceptors?.makeUpdatePolicyInterceptors() ?? [],
        wrapping: { try await self.updatePolicy(request: $0, context: $1) }
      )

    case "DeletePolicy":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_DeletePolicyRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_DeletePolicyResponse>(),
        interceptors: self.interceptors?.makeDeletePolicyInterceptors() ?? [],
        wrapping: { try await self.deletePolicy(request: $0, context: $1) }
      )

    case "CreateDefaultAttachment":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_CreateDefaultAttachmentRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_CreateDefaultAttachmentResponse>(),
        interceptors: self.interceptors?.makeCreateDefaultAttachmentInterceptors() ?? [],
        wrapping: { try await self.createDefaultAttachment(request: $0, context: $1) }
      )

    case "ListCommunityPolicyAttachments":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>(),
        interceptors: self.interceptors?.makeListCommunityPolicyAttachmentsInterceptors() ?? [],
        wrapping: { try await self.listCommunityPolicyAttachments(request: $0, context: $1) }
      )

    case "DeleteCommunityPolicyAttachments":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>(),
        interceptors: self.interceptors?.makeDeleteCommunityPolicyAttachmentsInterceptors() ?? [],
        wrapping: { try await self.deleteCommunityPolicyAttachments(request: $0, context: $1) }
      )

    case "UpdateCommunityPolicyAttachment":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>(),
        interceptors: self.interceptors?.makeUpdateCommunityPolicyAttachmentInterceptors() ?? [],
        wrapping: { try await self.updateCommunityPolicyAttachment(request: $0, context: $1) }
      )

    case "ListAttachedPolicies":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Com_Octopuscommunity_ListAttachedPoliciesRequest>(),
        responseSerializer: ProtobufSerializer<Com_Octopuscommunity_ListAttachedPoliciesResponse>(),
        interceptors: self.interceptors?.makeListAttachedPoliciesInterceptors() ?? [],
        wrapping: { try await self.listAttachedPolicies(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

public protocol Com_Octopuscommunity_ModerationPolicyServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'createPolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreatePolicyInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_CreatePolicyRequest, Com_Octopuscommunity_CreatePolicyResponse>]

  /// - Returns: Interceptors to use when handling 'listPolicies'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListPoliciesInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_ListPoliciesRequest, Com_Octopuscommunity_ListPoliciesResponse>]

  /// - Returns: Interceptors to use when handling 'updatePolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdatePolicyInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_UpdatePolicyRequest, Com_Octopuscommunity_UpdatePolicyResponse>]

  /// - Returns: Interceptors to use when handling 'deletePolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeletePolicyInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_DeletePolicyRequest, Com_Octopuscommunity_DeletePolicyResponse>]

  /// - Returns: Interceptors to use when handling 'createDefaultAttachment'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateDefaultAttachmentInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_CreateDefaultAttachmentRequest, Com_Octopuscommunity_CreateDefaultAttachmentResponse>]

  /// - Returns: Interceptors to use when handling 'listCommunityPolicyAttachments'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListCommunityPolicyAttachmentsInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_ListCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_ListCommunityPolicyAttachmentsResponse>]

  /// - Returns: Interceptors to use when handling 'deleteCommunityPolicyAttachments'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteCommunityPolicyAttachmentsInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsRequest, Com_Octopuscommunity_DeleteCommunityPolicyAttachmentsResponse>]

  /// - Returns: Interceptors to use when handling 'updateCommunityPolicyAttachment'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateCommunityPolicyAttachmentInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_UpdateCommunityPolicyAttachmentRequest, Com_Octopuscommunity_UpdateCommunityPolicyAttachmentResponse>]

  /// - Returns: Interceptors to use when handling 'listAttachedPolicies'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListAttachedPoliciesInterceptors() -> [ServerInterceptor<Com_Octopuscommunity_ListAttachedPoliciesRequest, Com_Octopuscommunity_ListAttachedPoliciesResponse>]
}

public enum Com_Octopuscommunity_ModerationPolicyServiceServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "ModerationPolicyService",
    fullName: "com.octopuscommunity.ModerationPolicyService",
    methods: [
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.createPolicy,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.listPolicies,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.updatePolicy,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.deletePolicy,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.createDefaultAttachment,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.listCommunityPolicyAttachments,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.deleteCommunityPolicyAttachments,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.updateCommunityPolicyAttachment,
      Com_Octopuscommunity_ModerationPolicyServiceServerMetadata.Methods.listAttachedPolicies,
    ]
  )

  public enum Methods {
    public static let createPolicy = GRPCMethodDescriptor(
      name: "CreatePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/CreatePolicy",
      type: GRPCCallType.unary
    )

    public static let listPolicies = GRPCMethodDescriptor(
      name: "ListPolicies",
      path: "/com.octopuscommunity.ModerationPolicyService/ListPolicies",
      type: GRPCCallType.unary
    )

    public static let updatePolicy = GRPCMethodDescriptor(
      name: "UpdatePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/UpdatePolicy",
      type: GRPCCallType.unary
    )

    public static let deletePolicy = GRPCMethodDescriptor(
      name: "DeletePolicy",
      path: "/com.octopuscommunity.ModerationPolicyService/DeletePolicy",
      type: GRPCCallType.unary
    )

    public static let createDefaultAttachment = GRPCMethodDescriptor(
      name: "CreateDefaultAttachment",
      path: "/com.octopuscommunity.ModerationPolicyService/CreateDefaultAttachment",
      type: GRPCCallType.unary
    )

    public static let listCommunityPolicyAttachments = GRPCMethodDescriptor(
      name: "ListCommunityPolicyAttachments",
      path: "/com.octopuscommunity.ModerationPolicyService/ListCommunityPolicyAttachments",
      type: GRPCCallType.unary
    )

    public static let deleteCommunityPolicyAttachments = GRPCMethodDescriptor(
      name: "DeleteCommunityPolicyAttachments",
      path: "/com.octopuscommunity.ModerationPolicyService/DeleteCommunityPolicyAttachments",
      type: GRPCCallType.unary
    )

    public static let updateCommunityPolicyAttachment = GRPCMethodDescriptor(
      name: "UpdateCommunityPolicyAttachment",
      path: "/com.octopuscommunity.ModerationPolicyService/UpdateCommunityPolicyAttachment",
      type: GRPCCallType.unary
    )

    public static let listAttachedPolicies = GRPCMethodDescriptor(
      name: "ListAttachedPolicies",
      path: "/com.octopuscommunity.ModerationPolicyService/ListAttachedPolicies",
      type: GRPCCallType.unary
    )
  }
}
